<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>icon.ico</ApplicationIcon>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlipnoteDotNet.Canvas\FlipnoteDotNet.Canvas.csproj" />
    <ProjectReference Include="..\FlipnoteDotNet.Core\FlipnoteDotNet.Core.csproj" />
    <ProjectReference Include="..\FlipnoteDotNet.Drawing\FlipnoteDotNet.Drawing.csproj" />
    <ProjectReference Include="..\FlipnoteDotNet.PropertyEditor\FlipnoteDotNet.PropertyEditor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App\Canvas\Assets\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>